// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240321092142_UpdateAllImageUrls")]
    partial class UpdateAllImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatisfactionRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = "220 hours",
                            ImageUrl = "https://localhost:7279/images/fullstack.svg",
                            Instructor = "Robert Fox",
                            Price = "$12.50",
                            SatisfactionRate = "94% (4.2K)",
                            Title = "Fullstack Web Developer Course from Scratch"
                        },
                        new
                        {
                            Id = 2,
                            Duration = "160 hours",
                            ImageUrl = "https://localhost:7279/images/htmlcss.svg",
                            Instructor = "Jenny Wilson & Marvin McKinney",
                            Price = "$15.99",
                            SatisfactionRate = "92% (3.1K)",
                            Title = "HTML, CSS, JavaScript Web Developer"
                        },
                        new
                        {
                            Id = 3,
                            Duration = "100 hours",
                            ImageUrl = "https://localhost:7279/images/thecomplete.svg",
                            Instructor = "Albert Flores",
                            Price = "$9.99",
                            SatisfactionRate = "98% (2.7K)",
                            Title = "The Complete Front-End Web Development Course"
                        },
                        new
                        {
                            Id = 4,
                            Duration = "160 hours",
                            ImageUrl = "https://localhost:7279/images/iosswift.svg",
                            Instructor = "Marvin McKinney",
                            Price = "$15.99",
                            SatisfactionRate = "92% (3.1K)",
                            Title = "iOS & Swift - The Complete iOS App Development Course"
                        },
                        new
                        {
                            Id = 5,
                            Duration = "160 hours",
                            ImageUrl = "https://localhost:7279/images/datascience.svg",
                            Instructor = "Esther Howard",
                            Price = "$11.20",
                            SatisfactionRate = "92% (3.1K)",
                            Title = "Data Science & Machine Learning with Python"
                        },
                        new
                        {
                            Id = 6,
                            Duration = "220 hours",
                            ImageUrl = "https://localhost:7279/images/creativecss.svg",
                            Instructor = "Robert Fox",
                            Price = "$10.50",
                            SatisfactionRate = "94% (4.2K)",
                            Title = "Creative CSS Drawing Course: Make Art With CSS"
                        },
                        new
                        {
                            Id = 7,
                            Duration = "160 hours",
                            ImageUrl = "https://localhost:7279/images/blender.svg",
                            Instructor = "Ralph Edwards",
                            Price = "$18.99",
                            SatisfactionRate = "92% (3.1K)",
                            Title = "Blender Character Creator v2.0 for Video Games Design"
                        },
                        new
                        {
                            Id = 8,
                            Duration = "100 hours",
                            ImageUrl = "https://localhost:7279/images/ultimate.svg",
                            Instructor = "Albert Flores",
                            Price = "$12.99",
                            SatisfactionRate = "98% (2.7K)",
                            Title = "The Ultimate Guide to 2D Mobile Game Development with Unity"
                        },
                        new
                        {
                            Id = 9,
                            Duration = "160 hours",
                            ImageUrl = "https://localhost:7044/images/jmeter.svg",
                            Instructor = "Jenny Wilson",
                            Price = "$14.50",
                            SatisfactionRate = "92% (3.1K)",
                            Title = "Learn JMETER from Scratch on Live Apps-Performance Testing"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
